### ISSUE TITLE
New "thing"

### ISSUE THREAD

**Issue by WardenCommander** [beatlepie/ONI-Mods#1]
Hey I love your mod,

could you add slider to set temperature under condensation point, over vaporiziation point?
and that consumption of power is calculated dynamically?

**Comment by beatlepie** [comment]
Sorry for the extremely delayed response, I have been busy with school and was not able to maintain the code or update it. 

My intention with the building was to make it similar to the in-game buildings, which is why has the same heat transfer rate as the original building. The power consumption code is similar to aquatuner code to make it work like other buildings in the game, it will heat up at a constant rate when being used.
